apiVersion: v1
kind: Secret
metadata:
  name: sec-{{ include "app-orgname" . }}
type: Opaque
data:
  {{- if eq .Values.appname "tls-ca" }}
  adminpw: {{ .Values.tlsca.adminpw | b64enc | quote }}
  {{- else if eq .Values.appname "enr-ca" }}
  adminpw: {{ .Values.enrollmentca.adminpw | b64enc | quote }}
  {{- end }}
